### ISSUE TITLE
LIBUSB::ERROR_ACCESS in libusb_claim_interface

### ISSUE THREAD

**Issue by perryn** [larskanis/libusb#11]
whenever I try to claim an interface on my OSX machine I get the above error. Below is an irb log showing the problem. Any idea whats wrong? TIA.

```
 > usb = LIBUSB::Context.new
 => #<LIBUSB::Context:0x007fcb428cb080 @ctx=#<FFI::Pointer address=0x007fcb4228a7a0>> 
> device = usb.devices(:idVendor => 0x1294, :idProduct =>0x1320).first
 => #<LIBUSB::Device 250/6 1294:1320 MAIL MAIL ? (HID (00,00))> 
> handle = device.open_interface(0)
LIBUSB::ERROR_ACCESS: LIBUSB::ERROR_ACCESS in libusb_claim_interface
	from /Users/perrynfowler/.rvm/gems/ruby-1.9.3-p286/gems/libusb-0.2.2/lib/libusb/constants.rb:46:in `raise_error'
	from /Users/perrynfowler/.rvm/gems/ruby-1.9.3-p286/gems/libusb-0.2.2/lib/libusb/dev_handle.rb:76:in `claim_interface'
	from /Users/perrynfowler/.rvm/gems/ruby-1.9.3-p286/gems/libusb-0.2.2/lib/libusb/device.rb:77:in `block in open_interface'
	from /Users/perrynfowler/.rvm/gems/ruby-1.9.3-p286/gems/libusb-0.2.2/lib/libusb/device.rb:62:in `open'
	from /Users/perrynfowler/.rvm/gems/ruby-1.9.3-p286/gems/libusb-0.2.2/lib/libusb/device.rb:76:in `open_interface'
	from (irb):5
	from /Users/perrynfowler/.rvm/rubies/ruby-1.9.3-p286/bin/irb:16:in `<main>'
```

**Comment by larskanis** [comment]
I hope this is solved, now.

**Comment by stefanahman** [comment]
I don't this is solved. I got the same error when recently trying to connect to a Extreme 3D Pro Joystick:

```ruby
± irb -Ilib -rlibusb                                                                                                                                                                                                            ruby-2.3.1
2.3.1 :001 > usb = LIBUSB::Context.new
 => #<LIBUSB::Context:0x007ff313800fa8 @ctx=#<FFI::Pointer address=0x007ff3114a5970>, @on_pollfd_added=nil, @on_pollfd_removed=nil, @hotplug_callbacks={}>
2.3.1 :002 > device = usb.devices(idVendor: 0x46D, idProduct: 0xC215).first
 => #<LIBUSB::Device 20/24 046d:c215 Logitech Logitech Extreme 3D ? (HID (00,00))>
2.3.1 :003 > device.open_interface(0)
LIBUSB::ERROR_ACCESS: LIBUSB::ERROR_ACCESS in libusb_claim_interface
	from /Users/stefanahman/.rvm/gems/ruby-2.3.1/gems/libusb-0.5.1/lib/libusb/constants.rb:62:in `raise_error'
	from /Users/stefanahman/.rvm/gems/ruby-2.3.1/gems/libusb-0.5.1/lib/libusb/dev_handle.rb:76:in `claim_interface'
	from /Users/stefanahman/.rvm/gems/ruby-2.3.1/gems/libusb-0.5.1/lib/libusb/device.rb:77:in `block in open_interface'
	from /Users/stefanahman/.rvm/gems/ruby-2.3.1/gems/libusb-0.5.1/lib/libusb/device.rb:62:in `open'
	from /Users/stefanahman/.rvm/gems/ruby-2.3.1/gems/libusb-0.5.1/lib/libusb/device.rb:76:in `open_interface'
	from (irb):3
	from /Users/stefanahman/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
```

**Comment by Geesu** [comment]
Also I have this problem when trying to connect to a Dymo S100 scale.
